Adam_optimizer:
  initial_lr: 0.01
  weight_decay: 1.0e-06
Dataset:
  num_locations: 20607
  num_users: 10000
  sequence_length: 20
  topic_num: 450
Embedding:
  base_dim: 8
Encoder:
  encoder_type: trans
Model:
  at_type: attn
  batch_size: 256
  epoch: 50
  seed: 1234
  test_epoch: 50
